---
- hosts: db
  become: yes
  gather_facts: no
  tasks:
    - name: ensure apt cache is up do date
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: ensure packages are installed
      apt:
        name:
          - postgresql
          - libpq-dev
          - python3-psycopg2
          - acl

- hosts: db
  become: yes
  become_user: postgres
  gather_facts: no
  vars:
    database: ads_database_production
    database_auth: auth_database_production
    user: ads
    password: qwerty
  tasks:
    - name: ensure database ads is created
      postgresql_db:
        name: '{{ database }}'
    - name: ensure user has access to ads db
      postgresql_user:
        db: '{{ database }}'
        name: '{{ user }}'
        password: '{{ password }}'
        priv: ALL

    - name: ensure database auth is created
      postgresql_db:
        name: '{{ database_auth }}'
    - name: ensure user has access to auth db
      postgresql_user:
        db: '{{ database_auth }}'
        name: '{{ user }}'
        password: '{{ password }}'
        priv: ALL

    - name: ensure user has no extra privelegues
      postgresql_user:
        name: '{{ user }}'
        # role_attr_flags: NOSUPERUSER,NOCREATEDB
        role_attr_flags: SUPERUSER,NOCREATEDB
    - name: ensure no other users has access to the database
      postgresql_privs:
        db: '{{ database }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent

    - name: ensure no other users has access to the database
      postgresql_privs:
        db: '{{ database_auth }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent

      
